# Generated by Django 5.0.1 on 2026-02-14 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Attribute Name')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime')], max_length=20, verbose_name='Data Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required')),
            ],
            options={
                'verbose_name': 'Attribute Definition',
                'verbose_name_plural': 'Attribute Definitions',
                'db_table': 'attribute_definitions',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Event Title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_datetime', models.DateTimeField(verbose_name='Start Date & Time')),
                ('end_datetime', models.DateTimeField(verbose_name='End Date & Time')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='Location')),
                ('is_online', models.BooleanField(default=False, verbose_name='Is Online Event')),
                ('online_link', models.URLField(blank=True, verbose_name='Online Meeting Link')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited capacity', null=True, verbose_name='Maximum Capacity')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('finished', 'Finished')], default='draft', max_length=20, verbose_name='Status')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/%Y/%m/', verbose_name='Cover Image')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views Count')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='categories.category', verbose_name='Category')),
                ('organizer', models.ForeignKey(limit_choices_to={'role': 'organizer'}, on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Organizer')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_string', models.CharField(blank=True, max_length=500, null=True)),
                ('value_integer', models.IntegerField(blank=True, null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='events.attributedefinition', verbose_name='Attribute')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='events.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event Attribute Value',
                'verbose_name_plural': 'Event Attribute Values',
                'db_table': 'event_attribute_values',
            },
        ),
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Result Title')),
                ('content', models.TextField(verbose_name='Result Content')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Published At')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='events.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event Result',
                'verbose_name_plural': 'Event Results',
                'db_table': 'event_results',
            },
        ),
        migrations.CreateModel(
            name='EventStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Stage Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Stage Order')),
                ('start_datetime', models.DateTimeField(verbose_name='Start Date & Time')),
                ('end_datetime', models.DateTimeField(verbose_name='End Date & Time')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='Location')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Leave blank to use event capacity', null=True, verbose_name='Stage Capacity')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='events.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event Stage',
                'verbose_name_plural': 'Event Stages',
                'db_table': 'event_stages',
                'ordering': ['event', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StageRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_type', models.CharField(choices=[('speaker', 'Speaker'), ('judge', 'Judge'), ('coach', 'Coach'), ('moderator', 'Moderator'), ('instructor', 'Instructor'), ('other', 'Other')], max_length=20, verbose_name='Role Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='stages/roles/%Y/%m/', verbose_name='Profile Image')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='events.eventstage', verbose_name='Stage')),
            ],
            options={
                'verbose_name': 'Stage Role',
                'verbose_name_plural': 'Stage Roles',
                'db_table': 'stage_roles',
                'ordering': ['stage', 'role_type'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_slug_930801_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_status_8890b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer'], name='events_organiz_1c7a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category'], name='events_categor_fd16be_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime'], name='events_start_d_2ddaa0_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattributevalue',
            index=models.Index(fields=['event', 'attribute'], name='event_attri_event_i_81e878_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventattributevalue',
            unique_together={('event', 'attribute')},
        ),
        migrations.AddIndex(
            model_name='eventstage',
            index=models.Index(fields=['event', 'order'], name='event_stage_event_i_dc8378_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventstage',
            unique_together={('event', 'order')},
        ),
    ]
