# Generated by Django 5.0.1 on 2026-02-14 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='confirmed', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes from the participant', verbose_name='Notes')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Checked In At')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
                'db_table': 'registrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'user'], name='registratio_event_i_92818b_idx'), models.Index(fields=['event', 'status'], name='registratio_event_i_6c7d81_idx'), models.Index(fields=['user', 'status'], name='registratio_user_id_d8db7a_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
