# Generated by Django 5.0.1 on 2026-02-14 14:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='Would Recommend')),
                ('organization_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Organization Rating')),
                ('content_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Content Rating')),
                ('venue_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Venue Rating')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this feedback is visible to public', verbose_name='Is Public')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='events.event', verbose_name='Event')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='registrations.registration', verbose_name='Registration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'feedbacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'is_public'], name='feedbacks_event_i_5bd680_idx'), models.Index(fields=['user'], name='feedbacks_user_id_25d2e0_idx'), models.Index(fields=['rating'], name='feedbacks_rating_109b6e_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
